[2021-08-04 14:33:08,362] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A 2021-08-04T14:09:54.460692+00:00 [queued]>
[2021-08-04 14:33:08,438] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A 2021-08-04T14:09:54.460692+00:00 [queued]>
[2021-08-04 14:33:08,438] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:33:08,439] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 14:33:08,439] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:33:08,603] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): training_model_A> on 2021-08-04T14:09:54.460692+00:00
[2021-08-04 14:33:08,630] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_A', '2021-08-04T14:09:54.460692+00:00', '--job-id', '2628', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmps43nh1d5', '--error-file', '/tmp/tmph2w92aqk']
[2021-08-04 14:33:08,631] {standard_task_runner.py:77} INFO - Job 2628: Subtask training_model_A
[2021-08-04 14:33:08,608] {standard_task_runner.py:52} INFO - Started process 129 to run task
[2021-08-04 14:33:08,937] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.training_model_A 2021-08-04T14:09:54.460692+00:00 [running]> on host 04479ea62028
[2021-08-04 14:33:09,328] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T14:09:54.460692+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T14:09:54.460692+00:00
[2021-08-04 14:33:09,329] {python.py:151} INFO - Done. Returned value was: 5
[2021-08-04 14:33:09,550] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_A, execution_date=20210804T140954, start_date=20210804T143308, end_date=20210804T143309
[2021-08-04 14:33:09,952] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 14:33:10,000] {local_task_job.py:149} INFO - Task exited with return code 0
