[2021-08-04 13:15:34,661] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-08-04T13:14:31.657682+00:00 [queued]>
[2021-08-04 13:15:34,681] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-08-04T13:14:31.657682+00:00 [queued]>
[2021-08-04 13:15:34,681] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:15:34,681] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 13:15:34,681] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:15:34,692] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): inaccurate> on 2021-08-04T13:14:31.657682+00:00
[2021-08-04 13:15:34,700] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', '2021-08-04T13:14:31.657682+00:00', '--job-id', '206', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmptvg5qz76', '--error-file', '/tmp/tmpz3hfucnk']
[2021-08-04 13:15:34,696] {standard_task_runner.py:52} INFO - Started process 6186 to run task
[2021-08-04 13:15:34,700] {standard_task_runner.py:77} INFO - Job 206: Subtask inaccurate
[2021-08-04 13:15:34,740] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.inaccurate 2021-08-04T13:14:31.657682+00:00 [running]> on host 04479ea62028
[2021-08-04 13:15:34,790] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T13:14:31.657682+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T13:14:31.657682+00:00
[2021-08-04 13:15:34,791] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-04 13:15:34,792] {subprocess.py:63} INFO - Running command: ['bash', '-c', " echo 'inaccurate'"]
[2021-08-04 13:15:34,800] {subprocess.py:74} INFO - Output:
[2021-08-04 13:15:34,801] {subprocess.py:78} INFO - inaccurate
[2021-08-04 13:15:34,801] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-04 13:15:34,829] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20210804T131431, start_date=20210804T131534, end_date=20210804T131534
[2021-08-04 13:15:34,854] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 13:15:34,873] {local_task_job.py:149} INFO - Task exited with return code 0
