[2021-08-04 13:27:06,975] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.accurate 2021-08-04T13:26:52.521259+00:00 [queued]>
[2021-08-04 13:27:07,058] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.accurate 2021-08-04T13:26:52.521259+00:00 [queued]>
[2021-08-04 13:27:07,059] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:27:07,059] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 13:27:07,059] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:27:07,086] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): accurate> on 2021-08-04T13:26:52.521259+00:00
[2021-08-04 13:27:07,094] {standard_task_runner.py:52} INFO - Started process 8683 to run task
[2021-08-04 13:27:07,108] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', '2021-08-04T13:26:52.521259+00:00', '--job-id', '951', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp41eehpv3', '--error-file', '/tmp/tmpqjjs1vs4']
[2021-08-04 13:27:07,108] {standard_task_runner.py:77} INFO - Job 951: Subtask accurate
[2021-08-04 13:27:07,288] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.accurate 2021-08-04T13:26:52.521259+00:00 [running]> on host 04479ea62028
[2021-08-04 13:27:07,664] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T13:26:52.521259+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T13:26:52.521259+00:00
[2021-08-04 13:27:07,667] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-04 13:27:07,668] {subprocess.py:63} INFO - Running command: ['bash', '-c', "echo 'accurate'"]
[2021-08-04 13:27:07,736] {subprocess.py:74} INFO - Output:
[2021-08-04 13:27:07,742] {subprocess.py:78} INFO - accurate
[2021-08-04 13:27:07,743] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-04 13:27:07,898] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20210804T132652, start_date=20210804T132706, end_date=20210804T132707
[2021-08-04 13:27:08,042] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 13:27:08,058] {local_task_job.py:149} INFO - Task exited with return code 0
