[2021-08-04 13:26:31,326] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A 2021-08-04T13:26:26.953118+00:00 [queued]>
[2021-08-04 13:26:31,443] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A 2021-08-04T13:26:26.953118+00:00 [queued]>
[2021-08-04 13:26:31,444] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:26:31,444] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 13:26:31,444] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:26:31,474] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): training_model_A> on 2021-08-04T13:26:26.953118+00:00
[2021-08-04 13:26:31,489] {standard_task_runner.py:52} INFO - Started process 8373 to run task
[2021-08-04 13:26:31,512] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_A', '2021-08-04T13:26:26.953118+00:00', '--job-id', '817', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpfj1dyqeu', '--error-file', '/tmp/tmp2j06ov4r']
[2021-08-04 13:26:31,512] {standard_task_runner.py:77} INFO - Job 817: Subtask training_model_A
[2021-08-04 13:26:31,748] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.training_model_A 2021-08-04T13:26:26.953118+00:00 [running]> on host 04479ea62028
[2021-08-04 13:26:32,092] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T13:26:26.953118+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T13:26:26.953118+00:00
[2021-08-04 13:26:32,093] {python.py:151} INFO - Done. Returned value was: 4
[2021-08-04 13:26:32,426] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_A, execution_date=20210804T132626, start_date=20210804T132631, end_date=20210804T132632
[2021-08-04 13:26:32,601] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 13:26:32,671] {local_task_job.py:149} INFO - Task exited with return code 0
